# Generated by Django 5.0.6 on 2024-06-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardekho_app', '0002_alter_carlist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlist',
            name='description',
            field=models.TextField(),
        ),
    ]
